"""Protocol exporters for Echo 525 (acoustic) and Opentrons OT-2 (pipetting).

Both exports consume a `vol_df` (per-run pipetting volumes from
`volumes.compute_volumes`) plus a plate assignment (from `plate.assign_plate`)
to map source → destination for each transfer.

The Echo exporter emits a Labcyte Echo-compatible transfer CSV; the OT-2
exporter emits a ready-to-edit Python Protocol API template. Neither file
hits hardware — both are artifacts a scientist pastes into their own system.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from screenase.config import ReactionConfig
from screenase.volumes import DNA_COL, PIPET_SUFFIX, TOTAL_COL, WATER_COL


def _reagent_pipet_cols(vol_df: pd.DataFrame) -> list[str]:
    """Per-reagent pipetting-volume columns, excluding bookkeeping totals."""
    return [
        c for c in vol_df.columns
        if c.endswith(PIPET_SUFFIX) and c not in (TOTAL_COL, WATER_COL, DNA_COL)
    ]


def build_echo_transfer_csv(
    vol_df: pd.DataFrame,
    plate_df: pd.DataFrame,
    *,
    source_plate_name: str = "Source[1]",
    destination_plate_name: str = "Destination[1]",
) -> str:
    """Emit a Labcyte-Echo transfer CSV.

    Columns: `Source Plate Name, Source Well, Destination Plate Name,
    Destination Well, Transfer Volume`. Transfer volume is in nanoliters (Echo
    convention), so the per-reagent pipetting µL gets * 1000.

    Source wells are assigned one per reagent: A1, A2, … A8 (the Echo typically
    holds 8 reagents on a source plate). DNA template + water are included as
    their own source wells to make the transfer list self-contained.
    """
    reagent_cols = _reagent_pipet_cols(vol_df) + [DNA_COL, WATER_COL]
    reagents = [c[: -len(PIPET_SUFFIX)] for c in reagent_cols]
    source_wells = {r: f"A{i + 1}" for i, r in enumerate(reagents)}

    # plate_df is Run-indexed; align by index to vol_df
    rows: list[dict[str, object]] = []
    for run_idx, vol_row in vol_df.iterrows():
        dest_well = plate_df.loc[run_idx, "well"] if run_idx in plate_df.index else f"{run_idx}"
        for reagent, col in zip(reagents, reagent_cols, strict=True):
            vol_uL = float(vol_row[col])
            if vol_uL <= 0:
                continue
            rows.append({
                "Source Plate Name": source_plate_name,
                "Source Well": source_wells[reagent],
                "Destination Plate Name": destination_plate_name,
                "Destination Well": dest_well,
                "Transfer Volume": round(vol_uL * 1000, 1),  # nL
                "Reagent": reagent,
            })
    return pd.DataFrame(rows).to_csv(index=False)


def write_echo_csv(
    vol_df: pd.DataFrame,
    plate_df: pd.DataFrame,
    out_path: Path | str,
    **kwargs: object,
) -> Path:
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_echo_transfer_csv(vol_df, plate_df, **kwargs))  # type: ignore[arg-type]
    return out


# ---------- OT-2 ----------

_OT2_TEMPLATE = '''"""Auto-generated Opentrons OT-2 protocol for Screenase run {run_id}.

Generated by screenase=={version}. Review before running on hardware:
- Tip racks + pipette mounts are declarations the user should match to their deck.
- Source wells are placeholders (A1..An on the reagent rack); swap to match
  your actual reagent positions.
"""

from opentrons import protocol_api

metadata = {{
    "protocolName": "Screenase DoE — {run_id}",
    "description": "DoE run plan auto-generated from screenase.",
    "apiLevel": "2.15",
}}


def run(ctx: protocol_api.ProtocolContext) -> None:
    # --- Deck layout (adjust slot numbers to your deck) ---
    reagent_rack = ctx.load_labware("opentrons_24_tuberack_nest_1.5ml_snapcap", 1)
    dest_plate = ctx.load_labware("corning_{plate_size}_wellplate_360ul_flat", 2)
    tip_rack = ctx.load_labware("opentrons_96_tiprack_20ul", 3)
    pipette = ctx.load_instrument("p20_single_gen2", "right", tip_racks=[tip_rack])

    # --- Reagent → source well map (edit to match your actual positions) ---
    sources = {sources_dict}

    # --- Transfers (one row per reagent × destination well) ---
{transfers}
'''


def build_ot2_protocol(
    vol_df: pd.DataFrame,
    plate_df: pd.DataFrame,
    cfg: ReactionConfig,
    *,
    run_id: str,
    version: str = "0.4.0",
    plate_size: int = 96,
) -> str:
    reagent_cols = _reagent_pipet_cols(vol_df) + [DNA_COL, WATER_COL]
    reagents = [c[: -len(PIPET_SUFFIX)] for c in reagent_cols]
    sources_dict = {r: f"A{i + 1}" for i, r in enumerate(reagents)}

    lines: list[str] = []
    for run_idx, vol_row in vol_df.iterrows():
        dest_well = plate_df.loc[run_idx, "well"] if run_idx in plate_df.index else f"{run_idx}"
        for reagent, col in zip(reagents, reagent_cols, strict=True):
            vol_uL = float(vol_row[col])
            if vol_uL <= 0:
                continue
            lines.append(
                f'    pipette.transfer({vol_uL:.2f}, '
                f'reagent_rack.wells_by_name()[sources["{reagent}"]], '
                f'dest_plate.wells_by_name()["{dest_well}"], '
                f'new_tip="always")'
            )
    return _OT2_TEMPLATE.format(
        run_id=run_id,
        version=version,
        plate_size=plate_size,
        sources_dict=repr(sources_dict),
        transfers="\n".join(lines) if lines else "    pass",
    )


def write_ot2_protocol(
    vol_df: pd.DataFrame,
    plate_df: pd.DataFrame,
    cfg: ReactionConfig,
    out_path: Path | str,
    **kwargs: object,
) -> Path:
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_ot2_protocol(vol_df, plate_df, cfg, **kwargs))  # type: ignore[arg-type]
    return out
